### ISSUE TITLE
Mux a specific session?

### ISSUE THREAD

**Issue by erikdebruin** [liveswitch/liveswitch-mux#2]
The idea is to pull all finished sessions off the Media Servers and put them on permanent storage as soon as possible.

The muxer in this scenario lives on a different computer and pulls sessions from storage, processes them on command and stores the product, discarding the session artifacts.

**Comment by avenema** [comment]
Right now, lsmux can pull from a single path using the `-i, --input-path` argument. The path can be local or remote, as long as it is accessible using standard file I/O paths.

What if there was an option to provide multiple input paths, one for each Media Server in the cluster?

**Comment by erikdebruin** [comment]
That would not be what I'm looking for. Right now our setup is to use a shared filesystem (EFS) for all Media Servers, so the muxer works fine as is.

However in an ideal world, we would be able to separate the muxing from the Media Servers altogether. In that scenario, the files would be put in an S3 bucket as soon as the session ends and removed from the Media sServers. This so there are no files lost when an instance is scaled in (which we account for now with a workaround). The muxer would live on a separate instance from the Media Server and a script would pull the session files from S3 and offer them to the muxer. For this it would be sweet if we could simple use an identifier as an argument and the muxer would use that to pick up the expected files...

**Comment by avenema** [comment]
Agreed, that sounds amazing.

The challenge we have is to ensure that lsmux knows _not_ to mux a session yet if recordings are still in progress, even if some recordings are complete (e.g. someone left).

Currently, the muxer relies on the log files to provide this information. Specifically, it gathers all the `startRecording` and `stopRecording` events along with their timestamps and uses that information to construct a timeline and infer a start/stop time for each "session" -- a period when recording was active for at least one participant in a given channel. The presence of a `startRecording` event without a corresponding `stopRecording` event implies that the recording is still active and ergo the session is as well.

I think we can make this work as long as there is a way to ship the recording events as well... Specifically, the `startRecording` event would need to ship as soon as it's available, followed by the recorded file with `stopRecording` metadata later.

**Comment by avenema** [comment]
@erikdebruin some options have been added that will hopefully help you with this use case.

1. Running `lsmux` with the `--dry-run` flag will give you JSON metadata on completed sessions without doing any actual muxing.
2. The JSON metadata now includes a deterministic `id` that uniquely identifies that particular session. This was already being calculated but not being included in the JSON output.
3. You can now target a specific session using that `id` by running `lsmux` with the `--session-id` argument.

Thinking in terms of your specific use case, you could:

1. Periodically run `lsmux --dry-run` on your shared file system (EFS) to determine which sessions are ready to be offloaded to object storage (S3).
2. Include the `id` from the JSON metadata as you offload, perhaps as a folder name.
3. Periodically copy completed sessions down from S3 and run `lsmux --session-id {id}` to generate the final session output.

**Comment by erikdebruin** [comment]
That sounds like it should do the trick. I'm going to play around with that.

Thank you!
